Add `DOCKER_MODS` support to Jellyfin rockon
rockstor/rockon-registry pull request #377
Opened 2024-07-04 05:02 UTC by jsutlovic

Simplifies configuration to enable hardware support in Jellyfin.

Empty string as a default seems to work reasonably, and adding hardware support works. 

> To ease and accelerate the PR submission, please use the template below to provide all requested information.
> You can find guidelines on which docker image to use in the [Rockstor's documentation](http://rockstor.com/docs/contribute_rockons.html#which-docker-image-should-i-use), 
> as well as examples of proper formatting in other rock-ons ([here](https://github.com/rockstor/rockon-registry/blob/master/teamspeak3.json)
> and [here](https://github.com/rockstor/rockon-registry/blob/master/nextcloud-official.json))

Fixes #376.

### General information on project
This pull request proposes to add a new rock-on for the following project: N/A

### Information on docker image
- docker image: https://hub.docker.com/r/linuxserver/jellyfin
- is an official docker image available for this project?: Yes

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [ ] Entry added to `root.json` in _alphabetical_ order (for new rock-on only) (N/A)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

2024-07-05 12:35 UTC, phillxnet commented
@jsutlovic Thanks for this contribution. I've added the "needs review" label and hopefully soon we can get this looked at. We are a small team so it takes a little while at time for reviews to emerge.

Could you detail if you have successfully tested this Rock-on change out; maybe via a locally hosted custom rock-on modified to not clash with the existing one?

2024-07-06 19:56 UTC, jsutlovic commented
@phillxnet I have tested it out locally, and it's been working quite well for some time. I'll see if I can get some screenshots uploaded of the updates.

2024-07-17 15:47 UTC, Hooverdan96 commented
@jsutlovic sorry for the delay, I was planning on reviewing it today. However, while the container starts and seems to be working, I can't connect to it (inspection shows ports are mapped, and with the `net=host` option this should be a trivial connection, but who knows).
For comparison, since I am running into the same issue with the currently published jellyfin container (which worked fine for me in the past), I suspect this is not related to your changes. I will try again hopefully this week, when I get a chance to clean up my testbed to ensure it's not creating problems of its own ...

2024-07-19 20:15 UTC, Hooverdan96 commented
Finally, I was able to run the Rockon, not sure anymore what the issue was. While I did not test the mod, I installed it once with and without, and in both cases, it seems that the resulting jellyfin Rockon was running just fine. So, @phillxnet I think this can be merged as an update to the current jellyfin Rockon that's being offered.

2024-07-22 14:21 UTC, phillxnet requested changes
@jsutlovic Thanks for presenting this welcome enhancement, and my apologies this has taken so long to be merged.

@Hooverdan96 Thanks for the review: much appreciated. I can get this published shortly, but for one niggle:

I get:

![empty-DOCKER_MODS-reveiw](https://github.com/user-attachments/assets/489137b5-191d-4b9d-b8f6-73d937ed197b)

Am I doing it wrong :). Or do we need a little more prompting? We had `(Optional)` in the description: but an entry of `""` was needed for me. Likely we have a few failures (outside this PR):

1. Failure to apply given default.
2. Refinement re optional entry: we  have a star against this entry as non-optional; hence the Web-UI reaction when nothing is entered.


So I'm a little reluctant to push this just yet as we lead folks into a corner - "... it's `Optional` but refuses no entry!  I don't know what to put in there ." type thing.

@Hooverdan96 & @FroggyFlox I'm a little rusty on our Rock-ons code: what is the recommendation/consensus here to get this PR released and not corner users? Do we just need a `Enter "" if not required` type thing until we have made rockstor-core improvements? I know we ask folks to put in defaults elsewhere currently: i.e. "This must be..." whatever instructions in description we have laying around.

2024-07-24 02:11 UTC, jsutlovic commented
@phillxnet @Hooverdan96 thanks both for the reviews and for taking a look, I haven't had much time myself to get back to this recently.

I agree that the optional field issue is what's causing the confusion here, and I'm happy to add some extra documentation to not confuse users. I'll take look at the other Rock-ons for guidance.

I have looked at the `rockstor-core` issue as well, and would be happy to contribute some time to moving that issue forward as I think it could be a significant improvement and it would make a number of other updates make sense as well.

2024-07-24 04:01 UTC, jsutlovic commented
Updated to match the default recommendation from the Handbrake rock-on:

<img width="742" alt="Screen Shot 2024-07-23 at 11 44 47 PM" src="https://github.com/user-attachments/assets/230d9822-9339-4591-8941-3ad7dc00913e">

2024-07-26 11:29 UTC, phillxnet approved these changes

2024-07-26 11:39 UTC, phillxnet commented
@jsutlovic Thanks for adding this work-around tool tip text. Tested as fine here also:

![empty-DOCKER_MODS-reveiw2](https://github.com/user-attachments/assets/ebd79ccf-c519-4e31-9fb3-1d2bddccb40a)

We are over due for some Rock-on improvements in rockstor-core. This last testing phase has been consumed with upping our dependencies/Python/Django etc: so at least we are now in a far better place to hopefully pick-up again on some Rock-ons improvements.

> I have looked at the `rockstor-core` issue as well, and would be happy to contribute some time to moving that issue forward as I think it could be a significant improvement and it would make a number of other updates make sense as well.

That would be great. Always short of human resources as it goes. Unsurprisingly. And do take care to grab latest testing branch if you end up finding time to have a look.

@Hooverdan96 Thanks for nudging this one along, and my apologies all-around for taking so long with get this merged and published.

2024-07-26 11:40 UTC, merged

2024-07-26 11:54 UTC, phillxnet commented
PR product PRODUCTION published.