Replace deprecated clear text password with hash
rockstor/rockon-registry pull request #389
Opened 2024-09-23 18:21 UTC by Hooverdan96

Fixes #388 .

### General information on project
- The developer deprecated clear text password earlier this year with a hash password that can be generated based on a script they are providing.
### Information on docker image
same image as before.

### Changes made to update Rockon definition:
- replace password parameter with password hash parameter
- update description with instructions for hash.
- fix indentation formatting (tab to space)
- increased version number

### Checklist
- [X] Passes [JSONlint](https://jsonlint.com) validation
- [X] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [X] `"description"` object lists and links to the docker image used
- [X] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [X] `"website"` object links to project's main website

### Testing
I have installed it using the same parameters as before, with the exception of the password now being entered as a hash value. Works well for me, connectivity from outside the network operates just as before it broke. The admin WebUI is accessible with the underlying password, so that transition works as well.

2024-09-23 19:09 UTC, Hooverdan96 commented
Here are some testing screenshots for setup and config. One thing I noticed is that the share mapped representation is incorrect in the summary page during configuration, they're swapped, all other parameters are in the column where they're supposed to be. This might require another small addition to what @phillxnet has already done recently.

I am not showing how I got the password hash, it's pretty self-explanatory on the link provided in the Rockon description.

![image](https://github.com/user-attachments/assets/df805542-8fd9-42e1-a7f8-9f29820d639b)

![image](https://github.com/user-attachments/assets/225c5af9-4294-4836-90c9-c563d01ac124)

![image](https://github.com/user-attachments/assets/810f136e-912f-4e53-8354-2e738c733e0c)
Here one can see the swapped parameter vs. mapped representation for the share:
![image](https://github.com/user-attachments/assets/fc79106a-895b-4e54-9340-f48603236d71)

![image](https://github.com/user-attachments/assets/2c0544aa-0019-4d06-a173-8c88f596f307)

![image](https://github.com/user-attachments/assets/3146fba8-024e-459e-af41-2f2a250cfba1)

![image](https://github.com/user-attachments/assets/3dffb5cc-98bc-4f70-984d-4111e87f8125)

If a previous instance was installed, the settings/keys will just show up and can continue to be used as before.

2024-09-24 10:56 UTC, phillxnet commented
@Hooverdan96 Just a quick note on:

> One thing I noticed is that the share mapped representation is incorrect in the summary page during configuration, they're swapped, all other parameters are in the column where they're supposed to be. This might require another small addition to what @phillxnet has already done recently.

In a recent comment on related improvements in this area: https://github.com/rockstor/rockstor-core/pull/2887#issuecomment-2291046151
I noticed a reversal of the Env entries, but Shares looked to be consistently mapped. Do you fancy creating an issue for this, given I failed to previously on noticing the Env reverse mapping. We likely have a few inadvertent reversals as I think a long time ago I only fixed one of a few of these types of reversals. So it would be good to established exactly where and what we are reversing. Above comment has an example of the Env switch that I failed to issue here on GitHub.

2024-09-24 11:32 UTC, phillxnet requested changes
@Hooverdan96 Thanks again for your continued efforts in maintaining this Rock-on. As always much appreciated.

Re:
> I am not showing how I got the password hash, it's pretty self-explanatory on the link provided in the Rockon description.

![WireGuard-new-link-re-password-prep](https://github.com/user-attachments/assets/ae0c49e6-1301-4e27-a8a1-3814dd82ad98)

I've only done a cursory pre-merge test here, to ensure the resulting Rock-on repo appears sane still. This looks to be the case. But I see a couple of minor link issues:

- The above indicated link gives a 404 (likely stuff has moved in the interim in the associated repo): https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md%20target=
- The GitHub repo link in the description has bugs:
- - Shows in text as: https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
- - Resolves to the local host thus: https://rleap15-6.lan/ghcr.io/wg-easy/wg-easy
for a  https://rleap15-6.lan instance.

Am I doing it wrong :).

2024-09-24 15:35 UTC, Hooverdan96 commented
Of course, you're not doing it wrong! I don't know what's happening. When I put my final html string into a validator, the links worked just fine. Of course I trusted that, and didn't retry this on a sample implementation. I'll address it.

2024-09-24 16:08 UTC, Hooverdan96 commented
I also created new issue [#2904](https://github.com/rockstor/rockstor-core/issues/2904) in the rockstor-core repo.

2024-11-01 10:35 UTC, phillxnet commented
@Hooverdan96 Appologies for the ages in getting back around to this PR:
Re:

> * The above indicated link gives a 404 (likely stuff has moved in the interim in the associated repo): https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md%20target=

Now works for me post your fix; and:

> * The GitHub repo link in the description has bugs:

I now get:

![wireguard-pr389-follow-up](https://github.com/user-attachments/assets/47b5acf0-26f9-41db-bf5e-d25ffbbf2774)

Where:
- "Emile Nijssen" resolves to: https://github.com/WeeJeWel - looks good.
- "ghcr.io/wg-easy/wg-easy" resolves to: https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy - also as intended by the looks of it.

So following on from my last review and you having already proven the actual function re install etc, I'll merge and get this out to PRODUCTION. Again my apologies here on the delay revisiting this Rock-on maintenance PR. And thanks again for all your efforts here and essentially everywhere else in the project. As always much appreciated.

2024-11-01 10:36 UTC, phillxnet approved these changes

2024-11-01 10:37 UTC, merged

2024-11-01 10:41 UTC, phillxnet commented
PR product PRODUCTION published.